sources:
  npm: true

allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense

reviewed:
  npm:
    - webpack # It is actually an MIT license source https://github.com/webpack/webpack/blob/master/LICENSE
    - ieee754 # It is actually a BSD 3-Clasue source https://github.com/feross/ieee754/blob/master/LICENSE
    - bcrypt-pbkdf # It is a combination of MIT and BSD 3-clause source https://github.com/joyent/node-bcrypt-pbkdf/blob/master/LICENSE
