[package]
name = "rss-feeds-provider"
version = "0.1.0"
edition = "2018"
authors = ["AlexRogalskiy"]

[[bin]]
name = "rss"
path = "rss/main.rs"

[dependencies]
regex = "1.4.3"
chrono = "0.4.19"
rss = { version = "1.5", features = ["from_url"] }