name: Latest articles and podcasts

on:
  workflow_dispatch:
  schedule:
    # Runs every day
    - cron: '0 2 * * *'

jobs:
  update-readme-with-posts:
    name: Update this repo's README with latest articles and podcasts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "HNRSS-POST-LIST"
          feed_list: "https://hnrss.org/newest"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "GUARDIAN-POST-LIST"
          feed_list: "https://www.theguardian.com/uk/rss"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "YCOMBINATOR-POST-LIST"
          feed_list: "https://news.ycombinator.com/rss"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "COMPUTERWORLD-POST-LIST"
          feed_list: "https://www.computerworld.com/index.rss"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "INFORMATIONWEEK-POST-LIST"
          feed_list: "https://www.informationweek.com/rss_simple.asp"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "INFOWORLD-POST-LIST"
          feed_list: "https://www.infoworld.com/index.rss"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "COMPUTERWEEKLY-POST-LIST"
          feed_list: "https://www.computerweekly.com/rss/All-Computer-Weekly-content.xml"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "REDDIT-POST-LIST"
          feed_list: "https://www.reddit.com/r/InformationTechnology/.rss?format=xml"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "ITWORLDCANADA-POST-LIST"
          feed_list: "https://www.itworldcanada.com/feed"
