name: comment-commands

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  process-comment:
    name: check-comment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cookie fortune teller
        uses: vincetse/fortune-cookie-action@v4

      - name: Updates file permissions
        run: chmod +x ./.github/scripts/process-comment.sh

      - name: Process comments
        run: ./.github/scripts/process-comment.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
