name: Update README on rss feeds

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */1 * *" # each day at 00:00 UTC

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      max-parallel: 1
      matrix:
        include:
          - bin: reviewgeek-rss
          - bin: poem-rss
    steps:
      - uses: actions/checkout@v2
      - name: Build
        # Replace "cargo build" to "cargo run" to run the script
        run: |
          cargo run --bin ${{ matrix.bin }}
        shell: bash

      - name: Prepare git config
        run: |
          git config --global core.autocrlf false
          git config --global core.ignorecase false
          git config --global help.autocorrect 1
          git config --global core.fileMode false
          git config --local user.email "github-actions@nullables.io"
          git config --local user.name "GitHub Actions"

      - name: Commit changeset
        run: |
          git add .
          git commit -am "[nodoc] Update feeds\n\nAdded feeds" || echo "No changes to commit"

      - name: Pull changeset
        run: |
          git pull origin master

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
