name: GitHub user contribution charts

on:
  workflow_dispatch:

jobs:
  graph-charts:
    name: Generate graph chart
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Create user contributions
        uses: alexrogalskiy/github-action-user-contribution@master
        with:
          userName: 'AlexRogalskiy'

      - name: Commit update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          skip_dirty_check: true
          commit_message: "docs: updates on GitHub charts\n\n Added information on GitHub charts"
          commit_options: '--no-verify --signoff'
          commit_user_name: GitHub Bot
          commit_user_email: github-actions@nullables.io
          commit_author: GitHub Bot <github-actions@nullables.io>
