name: label-sponsor

on:
  issues:
    types:
      - 'opened'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set sponsor label
        uses: JasonEtco/is-sponsor-label-action@70b4efb770e0ea4a7e9d4eff63bb5c89732a7819
        with:
          label: ":sparkling_heart: sponsor"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
