name: Licensed

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Check licenses
    runs-on: ubuntu-latest
    env:
      LICENSED_VERSION: 2.14.4
    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - name: Install licensed
        run: |
          cd ${{ runner.temp }}
          curl -Lfs -o licensed.tar.gz https://github.com/github/licensed/archive/2.14.4.tar.gz
          sudo tar -xzf licensed.tar.gz
          ls -la
          sudo mv ${{ runner.temp }}/licensed /usr/local/bin/licensed

      - run: licensed status
