name: Profile README stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # every week

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3.4.1
        with:
          node-version: '12.x'

      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@v1.1
        with:
          template: ./templates/statistics.md.tpl
          readme: ./templates/statistics.md
          token: ${{ secrets.USER_TOKEN }}

      - name: Get template data
        id: file_data
        run: |
          template_data=`cat ./templates/statistics.md | tr -d "\n\r"`
          template_data='<!--views:github-stats:start-->\n'"$template_data"'\n<!--views:github-stats:end-->'
          echo "${template_data//\"/\\\"}" > ./templates/statistics.md
          template_data=`cat ./templates/statistics.md`
          echo ::set-output name=current_data::${template_data}
        shell: bash

      - name: Find and Replace
        run: |
          npm install --global replace-in-files-cli
          replace-in-files --regex="<!--views:github-stats:start-->(.*?)<!--views:github-stats:end-->" --replacement="${{ steps.file_data.outputs.current_data }}" README.md
        shell: bash

      - name: Remove temporary files
        run: |
          rm -rf ./templates/statistics.md
        shell: bash

      - name: Commit update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          skip_dirty_check: true
          commit_message: "docs: updates on GitHub statistics\n\n Added information on GitHub statistics"
          commit_options: '--no-verify --signoff'
          commit_user_name: GitHub Bot
          commit_user_email: github-actions@nullables.io
          commit_author: GitHub Bot <github-actions@nullables.io>
