name: Screenshots for README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # every day

jobs:
  screenshot:
    name: Screenshot
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        width: [ 1200, 600 ]
        site: [ 'https://www.brainyquote.com/quote_of_the_day' ]
        prefix: [ 'brainyquote' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: ${{ matrix.site }}
          destination: screenshot-${{ matrix.prefix }}-${{ matrix.os }}-${{ matrix.width }}.png
          width: ${{ matrix.width }}
          full-page: true

      - name: Commit update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          skip_dirty_check: true
          skip_fetch: true
          commit_message: "docs: updates on GitHub screenshots\n\n Added information on GitHub screenshots"
          commit_options: '--no-verify --signoff'
          commit_user_name: GitHub Bot
          commit_user_email: github-actions@nullables.io
          commit_author: GitHub Bot <github-actions@nullables.io>
