name: Screenshots for README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # every day

jobs:
  screenshot:
    name: Screenshot
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        width: [ 600 ]
        height: [ 1020 ]
        site: [ 'https://www.brainyquote.com/quote_of_the_day' ]
        prefix: [ 'brainyquote' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: ${{ matrix.site }}
          destination: screenshot-${{ matrix.prefix }}-${{ matrix.os }}-${{ matrix.width }}-${{ matrix.height }}.png
          width: ${{ matrix.width }}
          height: ${{ matrix.height }}
          full-page: false

      - name: Find and copy images
        run: |
          cp -rf ${{ runner.temp }}/screenshot-*.png ${{ github.workspace }}/images/generated
        shell: bash

      - name: Prepare git
        run: |
          git config --global core.autocrlf false
          git config --global core.ignorecase false
          git config --global help.autocorrect 1
          git config --global core.fileMode false

      - name: Commit files
        run: |
          git config --local user.email "github-actions@example.com"
          git config --local user.name "GitHub Actions"
          git commit -am "[nodoc] Update screenshots\n\nAdded screenshot files" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
