name: Screenshots for README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *' # every day

jobs:
  screenshot-brainyquote:
    name: Screenshots
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - url: 'https://www.brainyquote.com/quote_of_the_day'
            width: 600
            height: 480
            tag: 'brainyquote'
    steps:
      - uses: actions/checkout@v2
      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: ${{ matrix.url }}
          destination: screenshot-${{ matrix.tag }}.png
          width: ${{ matrix.width }}
          height: ${{ matrix.height }}
          full-page: false

      - name: Find and copy images
        run: |
          cp -rf ${{ runner.temp }}/screenshot-*.png ${{ github.workspace }}/images/generated
        shell: bash

      - name: Prepare git config
        run: |
          git config --global core.autocrlf false
          git config --global core.ignorecase false
          git config --global help.autocorrect 1
          git config --global core.fileMode false
          git config --local user.email "github-actions@nullables.io"
          git config --local user.name "GitHub Actions"

      - name: Commit changeset
        run: |
          git add .
          git commit -am "[nodoc] Update screenshots\n\nAdded screenshot files" || echo "No changes to commit"

      - name: Pull changeset
        run: |
          git pull origin master

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
