name: Screenshots for README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # every day

jobs:
  screenshot:
    name: Screenshot
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        width: [ 1200, 600 ]
        site: [ 'https://www.brainyquote.com/quote_of_the_day' ]
        prefix: [ 'brainyquote' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: ${{ matrix.site }}
          destination: screenshot-${{ matrix.prefix }}-${{ matrix.os }}-${{ matrix.width }}.png
          width: ${{ matrix.width }}
          full-page: false

      - name: Find and copy images
        run: |
          cp -rf ${{ runner.temp }}/screenshot-*.png ${{ github.workspace }}/images/generated
        shell: bash

      - name: Prepare git
        run: |
          git config --global core.autocrlf false
          git config --global core.ignorecase false
          git config --global help.autocorrect 1
          git config --global core.fileMode false
          git config github.token ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch git commits
        run: |
          git pull origin master
        shell: bash

      - name: Commit update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          skip_dirty_check: true
          skip_fetch: true
          commit_message: "docs: updates on GitHub screenshots\n\n Added information on GitHub screenshots"
          commit_options: '--no-verify --signoff'
          commit_user_name: GitHub Bot
          commit_user_email: github-actions@nullables.io
          commit_author: GitHub Bot <github-actions@nullables.io>
