name: GitHub generate animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 */1 * *" # each day at 00:00 UTC

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: AlexRogalskiy
          svg_out_path: ./images/generated/github-contribution-grid-snake.svg

      - name: Get current working path
        id: file_data
        run: |
          cd ${{ github.workspace }}
          pwd
          ls -la
        shell: bash

      - name: Commit update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          skip_dirty_check: true
          skip_fetch: true
          commit_message: "docs: updates on GitHub animation\n\n Added information on GitHub animation"
          commit_options: '--no-verify --signoff'
          commit_user_name: GitHub Bot
          commit_user_email: github-actions@nullables.io
          commit_author: GitHub Bot <github-actions@nullables.io>
