name: Verify Licenses

on:
  push:
    branches:
      - master

jobs:
  licenses:
    name: Verify Gem Licenses
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check License Header
        uses: apache/skywalking-eyes@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
